#include "unity.h"

void test_system_manager_start_runtime_queues_start_normal_mode_when_loaded_settings_are_valid(void);
void test_system_manager_start_runtime_queues_start_setup_mode_with_loaded_settings(void);
void test_system_manager_enters_connecting_state_when_network_reports_connecting(void);
void test_system_manager_enters_connected_state_when_network_is_ready_with_no_departures(void);
void test_system_manager_enters_api_error_state_when_network_reports_api_error(void);
void test_system_manager_enters_no_departures_state_when_network_is_ready_with_empty_departures(void);
void test_system_manager_enters_departures_state_when_network_has_departures(void);
void test_system_manager_uses_default_arrow_mapping_when_flip_setting_is_off(void);
void test_system_manager_flips_arrow_mapping_when_setting_is_on(void);

int main(void)
{
    UNITY_BEGIN();

    RUN_TEST(test_system_manager_start_runtime_queues_start_normal_mode_when_loaded_settings_are_valid);
    RUN_TEST(test_system_manager_start_runtime_queues_start_setup_mode_with_loaded_settings);
    RUN_TEST(test_system_manager_enters_connecting_state_when_network_reports_connecting);
    RUN_TEST(test_system_manager_enters_connected_state_when_network_is_ready_with_no_departures);
    RUN_TEST(test_system_manager_enters_api_error_state_when_network_reports_api_error);
    RUN_TEST(test_system_manager_enters_no_departures_state_when_network_is_ready_with_empty_departures);
    RUN_TEST(test_system_manager_enters_departures_state_when_network_has_departures);
    RUN_TEST(test_system_manager_uses_default_arrow_mapping_when_flip_setting_is_off);
    RUN_TEST(test_system_manager_flips_arrow_mapping_when_setting_is_on);

    return UNITY_END();
}
